name: 'PHP_CodeSniffer Check with Annotations'
description: 'PHPCS checker with auto annotations out of the box'
author: 'Ilya Chekalsky'
inputs:
  enable_warnings:
    description: 'Enable checking for warnings (-w)'
    required: false
    default: ''
  standard:
    description: 'Standard to use (default to WordPress)'
    required: false
    default: 'WordPress'
  paths:
    description: 'Path(s) to check (space separated)'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'zap'
  color: 'purple'
